# Generated by Django 4.2.6 on 2023-11-06 16:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("user_contrib_app", "0002_contributor"),
        ("project_management_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="contributors",
            field=models.ManyToManyField(
                related_name="projects",
                through="user_contrib_app.Contributor",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
